name: Laravel CI GitHub Action

on: [pull_request, push]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' 
          
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Psalm
        run: ./vendor/bin/psalm --show-info=true

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse

      - name: Run Enlightn
        run: php artisan enlightn --ci --report
        env:
          ENLIGHTN_USERNAME: '${{ secrets.ENLIGHTN_USERNAME }}'
          ENLIGHTN_API_TOKEN: '${{ secrets.ENLIGHTN_API_TOKEN }}'

      - name: Run PHPInsights
        run: php artisan insights --no-interaction --min-quality=80 --min-complexity=90 --min-architecture=75 --min-style=95

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@0.1.0

      