name: Laravel Pint CI GitHub Action

on: [pull_request, push]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' 
          
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: PHP Insights
        uses: stefanzweifel/phpinsights-action@v1.1.1
        with: 
          php_version: '8.1'

      - name: Run Larastan
        uses: php-actions/phpstan@v2
        with: 
          php_version: '8.1'
          memory_limit: 256M

      - name: Run Psalm
        uses: docker://vimeo/psalm-github-actions
        with: 
          php_version: '8.1'

      - name: Run PHPInsights
        run: ./vendor/bin/phpinsights

      - name: Run Psalm
        run: ./vendor/bin/psalm --show-info=true

      - name: Run Enlightn
        run: php artisan enlightn

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@0.1.0

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse
      
